spring:
  datasource:
    url: jdbc:postgresql://postgres_hexagonal:5432/challenge_hexa
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
